default:
  model: openrouter/x-ai/grok-4.1-fast:free
  api_key: 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
  temperature: 0.7
agents:
  researcher:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  file_understanding:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  outline_creation:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  presentation:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
tools:
  summarizer:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  ppt_creator:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  img_describer:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0.5
