default:
  model: openrouter/x-ai/grok-4.1-fast:free
  api_key: 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
  temperature: 0.7
agents:
  researcher:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  file_understanding:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  outline_creation:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  presentation:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
tools:
  summarizer:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  ppt_creator:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0
  img_describer:
    model: openrouter/x-ai/grok-4.1-fast:free
    api_key: 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
    temperature: 0.5
